{
 "title": "Kubernetes / Kooper",
 "tags": [
  "kubernetes",
  "operators",
  "controllers",
  "kooper",
  "platform",
  "fit",
  "infrastructure"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kooper_controller_queued_events_total, cluster)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(kooper_controller_queued_events_total{cluster=\"${cluster}\"}, controller)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "${controller}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "controller" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ev/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kooper_controller_processed_event_duration_seconds_count{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}]))\nOR on() vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kooper_controller_queued_events_total{cluster=\"${cluster}\",requeue=\"true\",controller=\"${controller}\"}[1h])) or on() vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kooper_controller_processed_event_duration_seconds_count{cluster=\"${cluster}\",controller=\"${controller}\"}[1h]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kooper_controller_event_queue_length{cluster=\"${cluster}\",controller=\"${controller}\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kooper_controller_processed_event_duration_seconds_count{cluster=\"${cluster}\",success=\"false\", controller=\"${controller}\"}[${interval}]))\nOR on() vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(kooper_controller_processed_event_duration_seconds_count{cluster=\"${cluster}\", success=\"false\", controller=\"${controller}\"}[${interval}]))\n  /\n  sum(rate(kooper_controller_processed_event_duration_seconds_count{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}]))\n) OR on() vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kooper_controller_processed_event_duration_seconds_bucket{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}])) by (le)) OR on() vector(0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kooper_controller_event_in_queue_duration_seconds_bucket{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}])) by (le))\nOR on() vector(0)"
    }
   ]
  },
  {
   "title": "Event processing rate",
   "type": "timeseries",
   "description": "The rate of events processed per second including the errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ev/s" } },
   "targets": [
    {
     "expr": "sum(rate(kooper_controller_processed_event_duration_seconds_count{cluster=\"${cluster}\", success=\"true\", controller=\"${controller}\"}[${interval}]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(kooper_controller_processed_event_duration_seconds_count{cluster=\"${cluster}\", success=\"false\", controller=\"${controller}\"}[${interval}])) > 0",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Event processing latency",
   "type": "timeseries",
   "description": "The latency of the events processing",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kooper_controller_processed_event_duration_seconds_bucket{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kooper_controller_processed_event_duration_seconds_bucket{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kooper_controller_processed_event_duration_seconds_bucket{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Events in/out and queue length",
   "type": "timeseries",
   "description": "Events received (queued) VS processed (handled) inside the controller (and queue length on the right side)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ev/s" } },
   "targets": [
    {
     "expr": "0 - sum(rate(kooper_controller_processed_event_duration_seconds_count{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}]))",
     "legendFormat": "out (processed)"
    },
    {
     "expr": "sum(rate(kooper_controller_queued_events_total{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}]))",
     "legendFormat": "in (queued)"
    },
    {
     "expr": "kooper_controller_event_queue_length{cluster=\"${cluster}\", controller=\"${controller}\"}",
     "legendFormat": "queue length"
    }
   ]
  },
  {
   "title": "Waiting time events in queue",
   "type": "timeseries",
   "description": "The time an event will be waiting in the queue to be processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kooper_controller_event_in_queue_duration_seconds_bucket{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kooper_controller_event_in_queue_duration_seconds_bucket{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kooper_controller_event_in_queue_duration_seconds_bucket{cluster=\"${cluster}\", controller=\"${controller}\"}[${interval}])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}