{
 "title": "Rollify",
 "tags": [
  "rollify",
  "slok"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m" },
   {
    "name": "die_type",
    "label": "Die type",
    "query": {
     "query": "label_values(rollify_dice_roller_die_roll_results_total, die_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP RPS by handler",
   "type": "table",
   "description": "The RPS data by handler",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=\"rollify-server\"}[${interval}])) by (handler, method, code) > 0"
    }
   ]
  },
  {
   "title": "HTTP latency by handler",
   "type": "table",
   "description": "The HTTP latency data by handler",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service=\"rollify-server\"}[${interval}])) by (le, handler, method)) > 0) * 1000"
    }
   ]
  },
  {
   "title": "HTTP request rate",
   "type": "graph",
   "description": "HTTP API request rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=\"rollify-server\"}[${interval}])) by (code)",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=\"rollify-server\", code=~\"5..|429\"}[${interval}]))\n/\nsum(rate(http_request_duration_seconds_count{service=\"rollify-server\"}[${interval}]))",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "HTTP request latency",
   "type": "graph",
   "description": "HTTP API request latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service=\"rollify-server\",handler!~\".*/ws/.*\"}[${interval}])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{service=\"rollify-server\",handler!~\".*/ws/.*\"}[${interval}])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{service=\"rollify-server\",handler!~\".*/ws/.*\"}[${interval}])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Events and Websockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Number of subscriptions (Subscribers)",
   "type": "graph",
   "description": "The number of current connected subscribers",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rollify_subscriber_subscribers_subscribed{service=\"rollify-server\"}) by (subscription)",
     "legendFormat": "{{subscription}}"
    }
   ]
  },
  {
   "title": "Subscriptions per instance",
   "type": "bargauge",
   "description": "The number of subscriptions per instance",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rollify_subscriber_subscribers_subscribed{service=\"rollify-server\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Event publish rate (Notifier)",
   "type": "graph",
   "description": "The rate of events published",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ev/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rollify_notifier_operation_duration_seconds_count{service=\"rollify-server\"}[${interval}])) by (op)",
     "legendFormat": "{{op}}"
    },
    {
     "expr": "sum(rate(rollify_notifier_operation_duration_seconds_count{service=\"rollify-server\", success=\"false\"}[${interval}]))\n/\nsum(rate(rollify_notifier_operation_duration_seconds_count{service=\"rollify-server\"}[${interval}]))",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Event publish latency (Notifier)",
   "type": "graph",
   "description": "Event pusblish latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rollify_notifier_operation_duration_seconds_bucket{service=\"rollify-server\"}[${interval}])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(rollify_notifier_operation_duration_seconds_bucket{service=\"rollify-server\"}[${interval}])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(rollify_notifier_operation_duration_seconds_bucket{service=\"rollify-server\"}[${interval}])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Event handle rate (Subscriber/consumer)",
   "type": "graph",
   "description": "The rate of events handled by all the subscribers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ev/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rollify_subscriber_event_handler_duration_seconds_count{service=\"rollify-server\"}[${interval}])) by (subscription)",
     "legendFormat": "{{subscription}}"
    },
    {
     "expr": "sum(rate(rollify_subscriber_event_handler_duration_seconds_count{service=\"rollify-server\", success=\"false\"}[${interval}]))\n/\nsum(rate(rollify_subscriber_event_handler_duration_seconds_count{service=\"rollify-server\"}[${interval}]))",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Event handle latency (Subscriber/consumer)",
   "type": "graph",
   "description": "Event handle latency by all the subscribers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rollify_subscriber_event_handler_duration_seconds_bucket{service=\"rollify-server\"}[${interval}])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(rollify_subscriber_event_handler_duration_seconds_bucket{service=\"rollify-server\"}[${interval}])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(rollify_subscriber_event_handler_duration_seconds_bucket{service=\"rollify-server\"}[${interval}])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Repository Ops rate",
   "type": "table",
   "description": "The OPS data by opration",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(rollify_dice_roll_repository_operation_duration_seconds_count{service=\"rollify-server\"}[${interval}])) by (success, op)"
    }
   ]
  },
  {
   "title": "Repository latency by operation",
   "type": "table",
   "description": "The repository latency data by operation",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "(histogram_quantile(0.99, sum(rate(rollify_dice_roll_repository_operation_duration_seconds_bucket[${interval}])) by (le, op, success)) > 0) * 1000"
    }
   ]
  },
  {
   "title": "Repository operation rate",
   "type": "graph",
   "description": "repository operation rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rollify_dice_roll_repository_operation_duration_seconds_count{service=\"rollify-server\"}[${interval}])) by (op)",
     "legendFormat": "{{op}}"
    },
    {
     "expr": "sum(rate(rollify_dice_roll_repository_operation_duration_seconds_count{service=\"rollify-server\", success=\"false\"}[${interval}]))\n/\nsum(rate(rollify_dice_roll_repository_operation_duration_seconds_count{service=\"rollify-server\"}[${interval}]))",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Repository latency",
   "type": "graph",
   "description": "Repository  operation latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rollify_dice_roll_repository_operation_duration_seconds_bucket[${interval}])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(rollify_dice_roll_repository_operation_duration_seconds_bucket[${interval}])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(rollify_dice_roll_repository_operation_duration_seconds_bucket[${interval}])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Dice rolls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Dice roll rate",
   "type": "graph",
   "description": "The rate of rolled dice",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rollify_dice_roller_die_roll_results_total{service=\"rollify-server\"}[${interval}])) by (die_type) ",
     "legendFormat": "{{die_type}}"
    }
   ]
  },
  {
   "title": "Dice quantity dice roll",
   "type": "graph",
   "description": "These are the percentiles of the quantity of the dice rolls. e.g p99, means that the 99% of the dice rolls have N dice quantity per dice roll or less.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "dice" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rollify_dice_roller_dice_roll_die_quantity_bucket{service=\"rollify-server\"}[${interval}])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(rollify_dice_roller_dice_roll_die_quantity_bucket[${interval}])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(rollify_dice_roller_dice_roll_die_quantity_bucket[${interval}])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Dice buckets by value (${die_type})",
   "type": "bargauge",
   "description": "The % of dice roll results by result value",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 61 },
   "repeat": "die_type",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(rollify_dice_roller_die_roll_results_total{service=\"rollify-server\", die_type=\"${die_type}\"}[24h])) by (die_type, die_side) \n  /on(die_type) group_left \nsum(increase(rollify_dice_roller_die_roll_results_total{service=\"rollify-server\",die_type=\"${die_type}\"}[24h]))  by (die_type)\n",
     "legendFormat": "{{die_side}}"
    }
   ]
  }
 ]
}