{
 "title": "Network",
 "tags": [
  "home",
  "network",
  "ubiquiti"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(unpoller_device_uplink_latency_seconds[${interval}])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(unpoller_device_wan_receive_bytes_total[${interval}])) * 8",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(rate(unpoller_device_wan_transmit_bytes_total[${interval}])) * 8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(unpoller_client_uptime_seconds)",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(unpoller_client_satisfaction_ratio)",
     "legendFormat": "WiFi satisfaction"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU % usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unpoller_device_cpu_utilization_ratio) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory % usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unpoller_device_memory_utilization_ratio) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Wifi signal quality",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(\n  clamp_max(2 * (sum(unpoller_client_radio_signal_db) by (name) + 110), 100)[${interval}:]\n)",
     "legendFormat": "{{name}}"
    },
    { "expr": "vector(40)", "legendFormat": "low signal" }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unpoller_client_transmit_bytes_total[${interval}])) by (name) * 8 > 0",
     "legendFormat": "{{name}} Tx"
    },
    {
     "expr": "sum(rate(unpoller_client_receive_bytes_total[${interval}])) by (name) * 8 > 0",
     "legendFormat": "{{name}} Rx"
    }
   ]
  },
  {
   "title": "Clients data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wireless Devices",
     "type": "table-old",
     "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_receive_bytes_total{wired!=\"true\"})"
      },
      {
       "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_transmit_bytes_total{wired!=\"true\"})"
      },
      {
       "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_uptime_seconds{wired!=\"true\",site_name=~\"$Site\", name=~\"$Wireless\"})"
      }
     ]
    },
    {
     "title": "Wired Devices",
     "type": "table-old",
     "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_uptime_seconds{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})"
      },
      {
       "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_receive_bytes_total{wired=\"true\"})"
      },
      {
       "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_transmit_bytes_total{wired=\"true\"})"
      }
     ]
    }
   ]
  }
 ]
}