{
 "title": "Prometheus / Alerts",
 "tags": [
  "prometheus",
  "alerts",
  "infrastructure"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "All critical alerts",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", severity=~\"critical\"})"
    }
   ]
  },
  {
   "title": "Alerts by cluster",
   "type": "stat",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity=\"critical\", cluster != \"\"}) by (cluster) or ON() vector(0)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Critical alerts timeline",
   "type": "state-timeline",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity=\"critical\"}) by (alertname, cluster)",
     "legendFormat": "{{alertname}} ({{cluster}})"
    }
   ]
  },
  {
   "title": "Alerts timeline",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) by (alertname, severity,cluster)",
     "legendFormat": "{{alertname}} ({{cluster}})"
    }
   ]
  }
 ]
}